apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3jb8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-3jb8@sha256:41d6f9ca966e33730564aee9c45628611dd4e78b963046e6ee3b78f0597b1afc
        name: my-nodejs
        resources: {}
status: {}
